### PR TITLE
fix GuildScheduledEvents json reperesentation and modify function

### PR DESCRIPTION
**Pull request by HopeBaron**
* the description field is nullable
* fixed the modify function returning a common-level entity instead of core.

### CODE REVIEW

**Review by Lukellmann — APPROVED** [review]

**Comment by Lukellmann** [comment]
Are the docs again lying about nullability? Would probably also be a good idea to PR this to Discords docs.

**Comment by HopeBaron** [comment]
as per this payload 

```json
{
  //...
  "guild_scheduled_events": [
    {
      "status": 1,
      "sku_ids": [],
      "scheduled_start_time": "2023-01-13T20:00:00+00:00",
      "scheduled_end_time": "2023-01-13T21:00:00+00:00",
      "privacy_level": 2,
      "name": "test",
      "image_hash": null,
      "id": "931256650600415272",
      "guild_id": "699595207720566824",
      "entity_type": 3,
      "entity_metadata": {
        "location": "test"
      },
      "entity_id": null,
      "description": null,
      "channel_id": null
    }
  ]

  //...
}
```

**Comment by HopeBaron** [comment]
Scheduled Event object

**Comment by Lukellmann** [comment]
https://github.com/discord/discord-api-docs/pull/4608

**Pull request merged**
