### PR TITLE
Ephemeral embed support

### PR DESCRIPTION
**Pull request by HopeBaron**
Reference: [Message - Discord Devs Server ](https://discord.com/channels/613425648685547541/697138785317814292/837379075210215424)

### CODE REVIEW

**Comment by BartArys** [comment]
ephemerals still don't support attachments, right?

**Comment by DRSchlaubi** [comment]
> ephemerals still don't support attachments, right?

Doesn't seem like it to me: https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata

**Comment by BartArys** [comment]
> 
> 
> > ephemerals still don't support attachments, right?
> 
> Doesn't seem like it to me: https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata

Your link shows the data you can send in the *initial* response. I'm interested in the behaviour of this endpoint: <https://discord.com/developers/docs/interactions/slash-commands#create-followup-message>. Discord doesn't document differences between ephemeral and non-ephemeral followups, so in fixing this one inconsistency they might have fixed attachments as well.

**Comment by DRSchlaubi** [comment]
> > > ephemerals still don't support attachments, right?
> > 
> > 
> > Doesn't seem like it to me: https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionapplicationcommandcallbackdata
> 
> Your link shows the data you can send in the _initial_ response. I'm interested in the behaviour of this endpoint: https://discord.com/developers/docs/interactions/slash-commands#create-followup-message. Discord doesn't document differences between ephemeral and non-ephemeral followups, so in fixing this one inconsistency they might have fixed attachments as well.

I would assume that it's the same for responses and followups, but that would imply that the Discord API is consistent

**Comment by HopeBaron** [comment]
I've tested creating an ephemeral message with a file, got invalid body form in return.

**Comment by BartArys** [comment]
That's disappointing to hear.

**Review by BartArys — APPROVED** [review]

**Review by BartArys — APPROVED** [review]

**Pull request merged**
