### PR TITLE
Nitro Basic type

### PR DESCRIPTION
**Pull request by 0spura**
see https://github.com/discord/discord-api-docs/commit/48d3c2d324796d8236355262ace3b22c1d29acb0

### CODE REVIEW

**Comment by Lukellmann** [comment]
Please update the annotation [here](https://github.com/kordlib/kord/blob/0.8.x/common/src/main/kotlin/entity/DiscordUser.kt) instead and run `./gradlew apiDump` to regenerate `UserPremium.kt` and update the API dump.

**Comment by dookon** [comment]
> Please update the annotation [here](https://github.com/kordlib/kord/blob/0.8.x/common/src/main/kotlin/entity/DiscordUser.kt) instead and run `./gradlew apiDump` to regenerate `UserPremium.kt` and update the API dump.

Oh, sorry, I forgot

**Comment by Lukellmann** [comment]
Btw the reason the build passed is that the generated file you editied got overwritten to the old version during the build.

**Review by Lukellmann — APPROVED** [review]
Thanks!

**Pull request merged**
