### PR TITLE
Fix threads cache

### PR DESCRIPTION
**Pull request by Lukellmann**
This PR fixes a bug that threads weren't cached when receiving Guild events.
It also deprecates `Guild.threads` (it does not behave like one might expect) and instead replaces it with `GuildBehavior.cachedThreads`.

### CODE REVIEW

**Comment by HopeBaron** [comment]
Is there a way we could get these through rest?
if so we'd go with transforming this into a function that accepts a supplier

**Comment by HopeBaron** [comment]
your primary concern is weather you can cache it from gateway or not; it's up to the user to do it.

**Comment by Lukellmann** [comment]
What exactly does this mean for this PR?

**Comment by HopeBaron** [comment]
Looking back at this this looks just fine

**Comment by Lukellmann** [comment]
Can be merged then?

**Comment by gdude2002** [comment]
Would be great to see a merge for this

**Comment by gdude2002** [comment]
Thanks o7

**Pull request merged**
