### PR TITLE
Fix REST Module Rate Limiting Issues

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
The tests were updated because the tests themselves were borked: Now that the guild ID is used as a major parameter, the tests fail because the requests won't get rate limited.

* Fixes the same thing that was fixed in #699, so if this is merged, that PR can be closed.
* Use different buckets for different request identifiers. Before it was using a shared bucket, even if it was for different request identifiers, which caused all requests with the same bucket ID to halt until the rate limit was lifted, which sucked.
* I decreased the `autoBanRateLimiter` max requests from 25_000 to 10_000, because that's what's in the Discord's docs.
* Now Kord calculates the rate limit reset timer correctly. Before it was using the current time + `x-ratelimit-reset-after`, which is incorrect because it would mean that the reset timer is always in the future. Now the timer is calculated using `x-ratelimit-reset` + `x-ratelimit-reset-after`
* Now Kord correctly respects rate limits: If a resource is exausted (`x-ratelimit-remaining` == 0), Kord will wait for the rate limit timer before proceeding. If the `rateLimit` information is null, it will await every time, since we don't know the resource limit.

___

It all started with this [Kord's Guild](https://canary.discord.com/channels/556525343595298817/587324906702766226/1030111757689159790):

the bucket logs seem to be fine, but there is still a suspiciously high amount of suspended coroutines waiting for messages to be sent
```
14:15:09.196 [eventLoopGroupProxy-7-3] TRACE d.k.r.r.ParallelRequestRateLimiter - [BUCKET]:Bucket a06de0de4a08126315431cc0c55ee3dc waiting until Reset(value=2022-10-13T14:15:08.580456038Z)
14:15:09.457 [eventLoopGroupProxy-7-3] TRACE d.k.r.r.ParallelRequestRateLimiter - [RATE LIMIT]:[BUCKET]:Bucket a06de0de4a08126315431cc0c55ee3dc was exhausted until 2022-10-13T14:15:13.705031783Z
```

MY THEORY: It is ratelimiting requests incorrectly: It is basing on the bucket ID, but different routes have different ratelimit values, example:

```
curl https://discord.com/api/v10/channels/547119872568459284/messages
< x-ratelimit-bucket: a06de0de4a08126315431cc0c55ee3dc
< x-ratelimit-limit: 5
< x-ratelimit-remaining: 4
curl https://discord.com/api/v10/channels/739823666891849729/messages
< x-ratelimit-bucket: a06de0de4a08126315431cc0c55ee3dc
< x-ratelimit-limit: 5
< x-ratelimit-remaining: 4
curl https://discord.com/api/v10/channels/547119872568459284/messages
< x-ratelimit-bucket: a06de0de4a08126315431cc0c55ee3dc
< x-ratelimit-limit: 5
< x-ratelimit-remaining: 3
curl https://discord.com/api/v10/channels/739823666891849729/messages
< x-ratelimit-bucket: a06de0de4a08126315431cc0c55ee3dc
< x-ratelimit-limit: 5
< x-ratelimit-remaining: 3
```
Posting messages to different channels have different ratelimit values

But Kord is basing on the bucket ID, when in reality it should base on the "keys" (in this case, the channel ID) of the route

However, looking at the code... it seems that Kord already does this?

I think I found the issue...? :dogeweird:

when a bucket gets rate limited, every request suspends, even if it has a major ID in the route

I changed `AbstractRateLimiter` to
```kotlin
        fun updateReset(newValue: Reset) {
            reset.update { Reset(newValue.value + 1.minutes) }
        }
```

and did this

I found the issue (fr this time) :Alert:
```
Request Identifier: MajorParamIdentifier(route=Route(method:POST,path:/channels/{channel.id}/messages,mapper:ValueJsonMapper(strategy=dev.kord.common.entity.DiscordMessage$$serializer@b676ebf)), param=739823666891849729)
1671961687
Buckets: [dev.kord.rest.ratelimit.AbstractRateLimiter$Bucket@be27323]

Request Identifier: MajorParamIdentifier(route=Route(method:POST,path:/channels/{channel.id}/messages,mapper:ValueJsonMapper(strategy=dev.kord.common.entity.DiscordMessage$$serializer@b676ebf)), param=790676480640155700)
-895711629
Buckets: [dev.kord.rest.ratelimit.AbstractRateLimiter$Bucket@be27323]
```
They are using the same bucket instance :sad_cat3:

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
I made two new changes:
* I decreased the `autoBanRateLimiter` max requests from 25_000 to 10_000, because that's what the Discord's docs says.
* Now Kord calculates the rate limit reset timer correctly. Before it was using the current time + `x-ratelimit-reset-after`, which is incorrect because it would mean that the reset timer is always in the future. That bug also made Kord requests slower, because you were always waiting for `now + x-ratelimit-reset-after` when, in reality, you didn't need to wait. Now the timer is calculated using `x-ratelimit-reset` + `x-ratelimit-reset-after`
* Now Kord correctly respects rate limits: If a resource is exausted (`x-ratelimit-remaining` == 0), Kord will wait for the rate limit timer before proceeding.

**Comment by MrPowerGamerBR** [comment]
Missing Messages can trigger the "Bucket is exhausted, however we don't have any information about the reset timer"
```
21:54:24.883 [DefaultDispatcher-worker-16] WARN  d.k.r.r.ParallelRequestRateLimiter - [BUCKET]:Bucket missing (identity MajorParamIdentifier(route=Route(method:GET,path:/channels/{channel.id}/messages/{message.id},mapper:ValueJsonMapper(strategy=dev.kord.common.entity.DiscordMessage$$serializer@4ca8aa00)), param=358774895850815488)) is exausted, however we don't have any information about the reset timer
```

By looking at the headers, it doesn't seem to be consuming any resources

`x-ratelimit-limit=[5], x-ratelimit-remaining=[4], x-ratelimit-reset=[1665708871.193], x-ratelimit-reset-after=[5.000]`

So maybe we *shouldn't* update the bucket if the request was 404?

**Comment by MrPowerGamerBR** [comment]
I think this PR still has some issues, however the issue is trying to figure out why it is failing.

The issue that I've noticed is that sometimes the request just hangs on the awaitAndLock, maybe it is a race condition?

**Comment by Quantum64** [comment]
Would love to see this fixed soon. Is this change still in progress?

**Comment by MrPowerGamerBR** [comment]
@Quantum64 currently this PR is on hold. It does work but it has some issues, such as requests getting stuck forever, so for now I'm not using Kord for my bot.

**Comment by HopeBaron** [comment]
This will be closed to be added to a more up-to-date PR

**Pull request closed without merging**
