### PR TITLE
feature/gradle project accessors

### LINKED ISSUE #487: SelectMenuComponent is missing a disabled field
The SelectMenuComponent is missing the disabled field it is present in ComponentData and the discord docs say that the disabled field is applicable to Select Menus.

Edit: https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Review by Lukellmann — APPROVED** [review]

**Comment by HopeBaron** [comment]
This needs a merge I think you are more fit to do this since Im not sure what to remove :thinking:

**Comment by Lukellmann** [comment]
I think the merge is just removing the preview for version catalogs.

**Comment by DRSchlaubi** [comment]
> I think the merge is just removing the preview for version catalogs.

I don't see how it would do that

**Comment by Lukellmann** [comment]
> > I think the merge is just removing the preview for version catalogs.
> 
> I don't see how it would do that

The conflict is in `settings.gradle.kts`, right? Then just get rid of `enableFeaturePreview("VERSION_CATALOGS")`, `0.8.x` is on gradle 7.4 now, it's no longer a feature preview.

**Comment by DRSchlaubi** [comment]
Oh that's what you meant

**Pull request merged**
