### PR TITLE
0.7.0-RC

### PR DESCRIPTION
**Pull request by HopeBaron**

### CODE REVIEW

**Comment by BartArys** [comment]
The 0.7.0-RC tag already exists

**Comment by HopeBaron** [comment]
Should we go for RC2 then?

**Comment by BartArys** [comment]
Yup

**Comment by HopeBaron** [comment]
Done, thanks for the heads up!

**Comment by BartArys** [comment]
Missing a changelog as wel (have fun with that one)

**Comment by HopeBaron** [comment]
*Can't we do that on offical release*

**Pull request closed without merging**
