### PR TITLE
Add a nullable variant of `getAuthorAsMember`

### PR DESCRIPTION
**Pull request by NoComment1105**

### CODE REVIEW

**Review by Lukellmann — COMMENTED** [review]
looks good, but shouldn't the `getAuthorAsMember` function be deprecated then?

**Comment by NoComment1105** [comment]
Does it need to be? There are nullable and non null versions of a lot of other functions

**Comment by Lukellmann** [comment]
yeah those usually do different things, these two have the same code

**Comment by Lukellmann** [comment]
yeah, i think it's right to deprecate the other one, you usually want to have `OrNull` semantics (no exceptions as far as reasonable) either all the way or not at all, the existing function is a mix of both, your new one is clearly using `OrNull` semantics

**Review by Lukellmann — APPROVED** [review]
thanks :)

**Pull request merged**
