### PR TITLE
Add git-hooks for apiCheck

### PR DESCRIPTION
**Pull request by NoComment1105**
This is entirely because I forget and others do too, so it just makes it easier to avoid random build failures. Not necessary, just useful imo

### CODE REVIEW

**Comment by Lukellmann** [comment]
Hm, I'm not sure if I want to run `clean` on every commit. Couldn't you instead set up a git hook for yourself?

**Comment by NoComment1105** [comment]
Maybe I'm not sure. I could drop the clean from apiCheck and just make it check the API on each commit?

**Comment by DRSchlaubi** [comment]
I am unsure whether this is a great idea, because running Gradle in a git hook just takes forever and we do have CI for this

**Comment by HopeBaron** [comment]
The point of having the check is compare against the api file on the repo; the defeats the whole point of using it?

**Pull request closed without merging**
