### PR TITLE
fix small mistake in KordRestOnlyBuilder.kt

### PR DESCRIPTION
**Pull request by WinteryFox**
Fixes the chaining for one of the builder methods of KordRestOnlyBuilder

### CODE REVIEW

**Comment by Lukellmann** [comment]
Kord's builders are normally used in a Kotlin DSL style, they don't support the java-like builder chaining.
What's your usecase?

**Comment by WinteryFox** [comment]
Really? This builder doesn't seem to accept DSL. There's no secondary constructor that accepts DSL either.
`KordRestOnlyBuilder("token").requestHandler { something }.build()`

**Comment by Lukellmann** [comment]
It' supposed to be used this way:
```kotlin
val kord = Kord.restOnly {
    // ...
}
```

**Comment by WinteryFox** [comment]
Ohh that makes more sense, should probably change the visibility of this builder then?

**Comment by Lukellmann** [comment]
I don't see a problem with builders and their constructors being public.

**Comment by WinteryFox** [comment]
Makes sense, it would be nice to leave a note with a reference to the correct usage though.

**Comment by Lukellmann** [comment]
> Makes sense, it would be nice to leave a note with a reference to the correct usage though.

Would be nice if you were able to do this since you already opened this PR 😄

**Comment by Lukellmann** [comment]
Thanks :)

**Pull request merged**
