### PR TITLE
Fix / add entdpoints without authorization, remove shards field from GatwayResponse

### PR DESCRIPTION
**Pull request by Lukellmann**
- require authorization for `WebhookPatch`
- don't require authorization for `ExecuteWebhookPost`, `ExecuteSlackWebhookPost`, `ExecuteGithubWebhookPost`, `EditWebhookMessage`, `FollowupMessageCreate`, `FollowupMessageModify` and `FollowupMessageDelete` (see https://github.com/discord/discord-api-docs/pull/4349 regarding followups)
- remove `shards` field from `GatwayResponse`, see https://discord.com/developers/docs/topics/gateway#get-gateway or https://discord.com/api/v9/gateway
- make private shorthand getters in `EntitySupplier`s `inline`
- `null` as default for all `reason: String?` parameters

### CODE REVIEW

**Comment by HopeBaron** [comment]
https://discord.com/developers/docs/topics/gateway#get-gateway-bot
is the endpoint we use.

**Comment by Lukellmann** [comment]
> https://discord.com/developers/docs/topics/gateway#get-gateway-bot
> is the endpoint we use. so Shards are actually there

That endpoint returns a `BotGatewayResponse`, take a look at where `GatewayResponse` is used.

**Comment by DRSchlaubi** [comment]
> https://discord.com/developers/docs/topics/gateway#get-gateway-bot is the endpoint we use. so Shards are actually there

We don't actually use that class, the builder has "auto-sharding" but it doesn't decode to that class

**Comment by Lukellmann** [comment]
Kind of, it's only used in one Route that someone could call manually.

**Comment by HopeBaron** [comment]
The question is; if shards were of type int, how come it didn't throw on it when the field didn't exist :thinking:

**Comment by Lukellmann** [comment]
There are two endpoints for getting the gatway info, one without auth and one with auth: https://discord.com/developers/docs/topics/gateway#get-gateway.   
The shard info only exists on the one with auth, what I changed here is the response of the endpoint without auth. It didn't throw before because the enpoint without auth isn't used anywhere in Kord.   
You can verify that it currently throws by calling
```kotlin
val gatwayResponse = kord.rest.unsafe(Route.GatewayGet) {}
```

**Pull request merged**
