### PR TITLE
Discord only accepts language IDs separated by dashes when registering application command localizations

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
```
Invalid Form Body {"1":{"options":{"0":{"description_localizations":{"pt_BR":{"_errors":[{"code":"BASE_TYPE_CHOICES","message":"Value must be one of ('fi', 'cs', 'th', 'it', 'hi', 'bg', 'da', 'hu', 'en-GB', 'pt-BR', 'ru', 'ja', 'uk', 'es-ES', 'hr', 'ro', 'fr', 'nl', 'de', 'no', 'zh-TW', 'ko', 'el', 'tr', 'zh-CN', 'pl', 'en-US', 'vi', 'lt', 'sv-SE')."}]}}},"1":{"description_localizations":{"pt_BR":{"_errors":[{"code":"BASE_TYPE_CHOICES","message":"Value must be one of ('fi', 'cs', 'th', 'it', 'hi', 'bg', 'da', 'hu', 'en-GB', 'pt-BR', 'ru', 'ja', 'uk', 'es-ES', 'hr', 'ro', 'fr', 'nl', 'de', 'no', 'zh-TW', 'ko', 'el', 'tr', 'zh-CN', 'pl', 'en-US', 'vi', 'lt', 'sv-SE')."}]}}}}}}
```

### CODE REVIEW

**Review by Lukellmann — APPROVED** [review]
Thanks for catching this, I've only used German localizations so far, which won't trigger this problem.

**Comment by MrPowerGamerBR** [comment]
By the way @Lukellmann, I think that the RegEx should also be updated. The comment says " We accept both "_" and "-" as a separator, because Discord doesn't really document it", however the locale list documentation shows that all locales use a dash as a separator, so I don't think that they would magically change them to a underscore (unless if Discord mixes and matches the separators in different API endpoints?)

https://discord.com/developers/docs/reference#locales

**Comment by Lukellmann** [comment]
@DRSchlaubi, you implemeted `Locale`, what do you think?

**Comment by DRSchlaubi** [comment]
it wasnÄt documented at the time but still not all use dashes? am i missing something here?

**Pull request merged**
