### PR TITLE
Make StageChannel implement TopGuildMessageChannel

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by Lukellmann** [comment]
you need to commit the api dump from `./gradlew apiDump` to make the tests pass, the workflow was changed in #672

**Comment by DRSchlaubi** [comment]
> you need to commit the api dump from `./gradlew apiDump` to make the tests pass, the workflow was changed in #672

Oh so we no longer just do that on releases I see

**Comment by Lukellmann** [comment]
Could you squash and merge the next time @DRSchlaubi? That way the history will be cleaner on the main branch.

**Comment by DRSchlaubi** [comment]
> Could you squash and merge the next time @DRSchlaubi? That way the history will be cleaner on the main branch.

Sure

**Pull request merged**
