### PR TITLE
Bump `DeprecationLevel`s

### PR DESCRIPTION
**Pull request by Lukellmann**
`WARNING` -> `ERROR`
`ERROR` -> `HIDDEN`
`HIDDEN` -> remove

### CODE REVIEW

**Comment by Lukellmann** [comment]
`0.9.x` is the right target for this pr, right?

**Comment by HopeBaron** [comment]
Yes

**Comment by Lukellmann** [comment]
> Yes - Let's just wait for the MPP merge in a few first

on the cache project or here?

**Comment by HopeBaron** [comment]
Cache MPP > Kord MPP > Deprecation

**Comment by Lukellmann** [comment]
tbh i don't see why this should wait for mpp, imho it's better to have this as soon as possible after the release, so that we can base the further development on it

**Comment by HopeBaron** [comment]
Hmmm I think conflicts would be minimal if any

**Comment by Lukellmann** [comment]
> Hmmm I think conflicts would be minimal if any

that's what i thought too

**Pull request merged**
