### PR TITLE
Clean gradle files

### PR DESCRIPTION
**Pull request by DRSchlaubi**
This PR aims to improve the structure of the Gradle files by using Version Catalogs and extracting combined logic into the buildSrc folder

Current Issues
- The version bundles need to get added for each module manually
- How to properly addependencies (kotlin() function)?﻿

### CODE REVIEW

**Comment by BartArys** [comment]
Thanks for keeping our gradle files up to date, could you elaborate on the issues you're having right now?

**Comment by DRSchlaubi** [comment]
> Thanks for keeping our gradle files up to date, could you elaborate on the issues you're having right now?

Sure.

For one we have Gradle plugin Versions in the normal build gradle.kts files and in the buildsrc build.gradle.kts
These are required for the plugin scrips to work and can't access the usual versions object in buildSRac as buildSrc buildscript doesn't have access to buildSrc


Then I use the kotlin() function sometimes and don't really know how to specify that

Last but not least the common and test lib bundles need to be applied manually. The reason being that the libs extension gets registered after buildSrc scripts and after subprojects

**Comment by HopeBaron** [comment]
Can you modify the voice module as well please?

**Comment by DRSchlaubi** [comment]
> Can you modify the voice module as well please?

Uuuuhm in theory yes, but it will take a few days probably

**Comment by HopeBaron** [comment]
Take all the time you need, just inform me when done so we can merge this

**Comment by DRSchlaubi** [comment]
> Take all the time you need, just inform me when done so we can merge this

done

**Review by HopeBaron — APPROVED** [review]

**Pull request merged**
