### PR TITLE
Add API version configuration

### PR DESCRIPTION
**Pull request by Lukellmann**
This PR allows to configure which versions of Discord's APIs Kord uses.
This is achieved by changing the properties `REST_VERSION`, `GATEWAY_VERSION` or `VOICE_GATEWAY_VERSION` of the `KordConfiguration` object:
```kotlin
object KordConfiguration {
    var REST_VERSION: Int
    var GATEWAY_VERSION: Int
    var VOICE_GATEWAY_VERSION: Int
}
```

Reading the REST version from the environment variable `dev.kord.rest.version` is removed.

`DefaultGateway.Companion.invoke` now no longer uses an unversioned gateway url.

### CODE REVIEW

**Comment by Lukellmann** [comment]
This is a first draft of the configuration options I mentioned [here](https://github.com/kordlib/kord/pull/575#issuecomment-1079787757).

Would be nice to get some feedback on this. Are there more things that could be configured in this way?
(@HopeBaron @DRSchlaubi @MrPowerGamerBR)

**Comment by Lukellmann** [comment]
If there are no concerns about the design of this (mutable properties in an object), I would say this is ready for review.

**Comment by HopeBaron** [comment]
Looks fine :+1:

**Comment by Lukellmann** [comment]
[This PR](https://github.com/discord/discord-api-docs/pull/5012) removed the separately listed Gateway version, should we also only have one property for this?

**Comment by Lukellmann** [comment]
> [This PR](https://github.com/discord/discord-api-docs/pull/5012) removed the separately listed Gateway version, should we also only have one property for this?

I thought about this and we probably shouldn't - if you want to change the version for only one of them you should be free to do so.

**Comment by HopeBaron** [comment]
Do you mean to have a fixed set of versions?

**Comment by Lukellmann** [comment]
I meant always using the same version for gateway and rest, but I think we should allow changing them independently.

**Comment by HopeBaron** [comment]
Yeah it looks fine; we just need to fix the conflicts to go

**Comment by Lukellmann** [comment]
Will do today/tomorrow 👍

**Comment by Lukellmann** [comment]
Done

**Pull request merged**
