### PR TITLE
Don't use value class `Reset` with `AtomicRef`

### PR DESCRIPTION
**Pull request by DRSchlaubi**
The use of value classes for the `Reset` class has already caused issues implementing #855. However, it was isolated to native platforms. Unfortunately, this behavior will become a compiler error soon, so we need to change it. This can be achieved by simply using the backing `Instant` instead of `Reset` with `AtomicRef`.

# Related Issues
#855 
#69 
Kotlin/kotlinx-atomicfu#291
[KT-61584](https://youtrack.jetbrains.com/issue/KT-61584)

### CODE REVIEW

**Comment by lukellmann** [comment]
if we have a breaking change here anyway, do we really need this wrapper around `Instant` at all?

**Comment by DRSchlaubi** [comment]
Probably not

**Comment by lukellmann** [comment]
let me see what i can do then

**Comment by lukellmann** [comment]
ok, so i kept `Reset` as an `@JvmInline value class`, deprecated it and replaced the usages with plain `Instant`. with some annotation trickery, i think i managed to preserve binary compatibility, so only source compatibility is broken now (which is easier to fix).

**Comment by lukellmann** [comment]
can you take a look @DRSchlaubi?

**Comment by lukellmann** [comment]
wait a second, i just noticed that we don't even have to change any public api, we can just box/unbox the `Reset.value` internally without api changes

**Review by lukellmann — APPROVED** [review]
simply using the backing `Instant` should do the job, what do you think @DRSchlaubi?

**Comment by DRSchlaubi** [comment]
Looks good

**Pull request merged**
