### PR TITLE
Add disabled property to SelectMenuComponent

### LINKED ISSUE #487: SelectMenuComponent is missing a disabled field
The SelectMenuComponent is missing the disabled field it is present in ComponentData and the discord docs say that the disabled field is applicable to Select Menus.

Edit: https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure

### PR DESCRIPTION
**Pull request by DRSchlaubi**
Fix #487

### CODE REVIEW

**Review by Lukellmann — COMMENTED** [review]
Maybe name it `isDisabled`?

**Comment by DRSchlaubi** [comment]
Slash commands called it disabled too

**Comment by Lukellmann** [comment]
I'm fine with that too, just noticed that some names in core entities are a little different, like `isNsfw` or `isArchived` in `ThreadChannel`.  
The documentation of `disabled` also makes it seem like the property is mutable.

**Comment by HopeBaron** [comment]
do we have it in create/modify requests?

**Comment by Lukellmann** [comment]
> Slash commands called it disabled too

And in `Button` it's called `disabled` too, so don't mind my naming suggestion, would still change the doc comment though.

**Comment by Lukellmann** [comment]
> do we have it in create/modify requests?

Seems so, they use `SelectMenuBuilder` https://github.com/kordlib/kord/blob/0.8.x/rest/src/main/kotlin/builder/component/SelectMenuBuilder.kt

**Comment by HopeBaron** [comment]
Ya both had different PRs under the same tasks  you got me comparing both :P

**Pull request merged**
