### PR TITLE
Refactor `files` and `addFile` methods in the REST requests to avoid code duplication

### PR DESCRIPTION
**Pull request by MrPowerGamerBR**
This is blocked by https://github.com/kordlib/kord/pull/228 and https://github.com/kordlib/kord/pull/229

A lot of request builders in Kord have the same `files` list and the same implementation for the `addFile` methods, to avoid code duplication, this PR adds a `MultipleAttachmentsRequest` (I think this is a bad name so if anyone has a better name, please tell me!) which adds default implementations to the `addFile` methods, which should help avoid code duplication.

This will also help if more file related methods are added (example: Loading a file from a `URL`), this way we only need to change the interface instead of adding the new method for every request that has a `files` list. 😊

### CODE REVIEW

**Comment by HopeBaron** [comment]
I doubt it's worth adding, but a better name would be `MultipartBuilder` or the like it's not a request.

**Comment by MrPowerGamerBR** [comment]
> I doubt it's worth adding

Keep in mind that there will be other requests that aren't implemented in Kord yet that can also use the `MultipartBuilder` (Example: Webhook File Sending, Webhook Message File Editing, etc), that's why I thought that it would be nice to keep all the file related stuff in a single interface.

And yes, `MultipartBuilder` is a better name :)

**Comment by HopeBaron** [comment]
I'm waiting for the name change to merge this. I've seen the issue related to adding multiple file support.

**Comment by BartArys** [comment]
I'd be careful with the `files` property. In it's not unthinkable to run into a builder that can only accept a maximum of one file, in which case the aim of the interface (to unite all file-addable builders) would fail. And would `addFile` be the correct term for a builder than can only accept one file max?

In essence what you're PR'ing is a `FileAddable` interface, calling it a `MultipartBuilder` or a `MultipleAttachmentsRequest` would be inaccurate, as it could be applied to situations that are neither multiplart form requests (rather unlikely) or related to attachments (consider programmatically changing the icon of a server).

> this way we only need to change the interface instead of adding the new method for every request that has a files list.

If we do introduce this interface, we shouldn't strive to mindlessly break it by adding new methods to it.

---

I don't see people writing much code against such a "file-addable" interface, nor implementing it themselves, the only proper benefit would be extension functions that carry over between builders.

**Pull request closed without merging**
